FROM python:3.12-slim AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \ 
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app


WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

RUN pip install "fastapi[standard]" uvicorn

COPY src/ .


EXPOSE 8000 





CMD [ "unvicorn", "main:app", "--reload", "--port", "8000", "--host", "0.0.0.0" ]











